package com.mineinspect.app.navigation

object Routes {
    const val LOGIN = "login"
    const val HOME = "home"
    const val MINE_BRIEFING = "mine_briefing/{mineId}"
    const val GPS_GATE = "gps_gate/{inspectionId}"
    const val ACTIVE_TRACKING = "active_tracking/{inspectionId}"
    const val ROUTE_MAP = "route_map?inspectionId={inspectionId}"
    const val AREAS_COVERAGE = "areas_coverage/{inspectionId}"
    const val SECTION_START = "section_start/{inspectionId}/{sectionId}"
    const val SECTION_MONITORING = "section_monitoring/{inspectionId}/{sectionId}"
    const val SECTION_CHECKS_MENU = "section_checks_menu/{inspectionId}/{sectionId}"
    const val ANOMALY_WARNING = "anomaly_warning"
    const val RANDOM_EVIDENCE = "random_evidence/{inspectionId}/{sectionId}"
    const val EVIDENCE_CAPTURE = "evidence_capture/{inspectionId}/{sectionId}"
    const val EVIDENCE_DETAILS = "evidence_details/{evidenceId}"
    const val PPE_VERIFICATION = "ppe_verification/{inspectionId}/{sectionId}"
    const val MANUAL_OBSERVATION = "manual_observation/{inspectionId}/{sectionId}"
    const val MEASUREMENT_ENTRY = "measurement_entry/{inspectionId}/{sectionId}"
    const val WORKER_VERIFICATION = "worker_verification/{inspectionId}/{sectionId}"
    const val SECTION_COMPLETION = "section_completion/{inspectionId}/{sectionId}"
    const val INSPECTION_SUMMARY = "inspection_summary"
    const val FINAL_REVIEW = "final_review/{inspectionId}"
    const val FINAL_LOCATION_CHECK = "final_location_check/{inspectionId}"
    const val OFFLINE_SAVE = "offline_save"
    const val SYNCHRONIZATION = "synchronization/{inspectionId}"
    const val SUBMISSION_COMPLETE = "submission_complete"

    fun mineBriefing(mineId: String) = "mine_briefing/$mineId"
    fun gpsGate(inspectionId: String) = "gps_gate/$inspectionId"
    fun activeTracking(inspectionId: String) = "active_tracking/$inspectionId"
    fun routeMap(inspectionId: String? = null) =
        if (inspectionId != null) "route_map?inspectionId=$inspectionId" else "route_map"
    fun areasCoverage(inspectionId: String) = "areas_coverage/$inspectionId"
    fun sectionStart(inspectionId: String, sectionId: String) = "section_start/$inspectionId/$sectionId"
    fun sectionMonitoring(inspectionId: String, sectionId: String) = "section_monitoring/$inspectionId/$sectionId"
    fun sectionChecksMenu(inspectionId: String, sectionId: String) = "section_checks_menu/$inspectionId/$sectionId"
    fun randomEvidence(inspectionId: String, sectionId: String) = "random_evidence/$inspectionId/$sectionId"
    fun evidenceCapture(inspectionId: String, sectionId: String) = "evidence_capture/$inspectionId/$sectionId"
    fun evidenceDetails(evidenceId: String) = "evidence_details/$evidenceId"
    fun ppeVerification(inspectionId: String, sectionId: String) = "ppe_verification/$inspectionId/$sectionId"
    fun manualObservation(inspectionId: String, sectionId: String) = "manual_observation/$inspectionId/$sectionId"
    fun measurementEntry(inspectionId: String, sectionId: String) = "measurement_entry/$inspectionId/$sectionId"
    fun workerVerification(inspectionId: String, sectionId: String) = "worker_verification/$inspectionId/$sectionId"
    fun sectionCompletion(inspectionId: String, sectionId: String) = "section_completion/$inspectionId/$sectionId"
    fun finalReview(inspectionId: String) = "final_review/$inspectionId"
    fun finalLocationCheck(inspectionId: String) = "final_location_check/$inspectionId"
    fun synchronization(inspectionId: String) = "synchronization/$inspectionId"
}
